server:
  port: 8089  # Gateway will run on 8086

spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8083
          predicates:
            - Path=/accounts/**

        - id: loan-service
          uri: http://localhost:8084
          predicates:
            - Path=/loans/**
